### ISSUE TITLE
Errore nella chiave dell'oggetto country in fetch-page.

### ISSUE THREAD

**Issue by buischiomassimo** [atoms-studio/gluon#1]
Ottengo l'errore
`Cannot read property 'toUpperCase' of undefined` alle righe 56, 74, 75 del file **fetch-page.js** del middleweare. 

Viene usato la chiave "code" `country.code.toUpperCase()` mentre nel contentModel viene usata la chiave `iso`, quindi il codice dovrebbe essere `country.iso.toUpperCase()`. 

Credo sia più corretto dare la possibilità di customizzare questa proprietà. E' possibile?

**Comment by reegodev** [comment]
Fixed in 0.4.2!
